version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pslmp_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: pslmp
    ports:
      - "5432:5432"
    volumes:
      - pslmp_data:/var/lib/postgresql/data

volumes:
  pslmp_data: # This ensures your data isn't deleted when the container stops